### ISSUE TITLE
Multiple bundles with the same label break ERD generation

### ISSUE THREAD

**Issue by TravisCarden** [acquia/drupal-spec-tool#10]
If you give two bundles the same label it will confuse the queries and break the auto-generated entity relationship diagram (ERD), even if they're of different content entity types (e.g., a content type and a vocabulary). It's probably best from a UX perspective not to name multiple things identically. Nevertheless, this can probably be fixed by using machine names as aliases in the PlantUML.

**Comment by darkcody** [comment]
Note: this can also break generated behat tests, since the VLOOKUP for entity type on the "Fields" sheet could be incorrect when bundle labels are duplicated.

@TravisCarden, my current workaround is to update the bundle label from the Queries sheet to include the entity type whenever the bundle label is duplicated. E.g. "Video (Content Type)" and "Video (Media)" when both a media type and content type labeled "Video" were added to the bundles sheet. Non-duplicated labels are left as is.

To do so, I've replaced the formula from `Queries!A2` with the following:
```
={
  "Bundles", "Types";
  IFERROR(SORT(FILTER(
    ARRAYFORMULA({
      ARRAYFORMULA(
        IF(
          COUNTIF(Bundles!B:B,Bundles!B:B)>1,
          CONCAT(Bundles!B:B, " (" & Bundles!Q:Q &")"),
          Bundles!B:B
        )
      ),
      Bundles!Q:Q
    }),
    ROW(Bundles!A:A) > 1
  )), {"", ""})
}
```

**Comment by kducharm** [comment]
@darkcody Thanks for this workaround, just ran into the same issue and seems to work like a charm!

**Comment by TravisCarden** [comment]
Thank you for this work, @darkcody! I like the idea of disambiguating by putting the content entity type in parentheses. I've decided to adopt that approach unconditionally (i.e., whether or not a bundle name is a "duplicate"). I'm working on implementing the change. Since the change will require non-backward-compatible changes to both the spreadsheet and the Behat contexts, this will require a major version release. I'll keep you up-to-date on my progress.

**Comment by TravisCarden** [comment]
Okay, @darkcody, the fix has been integrated into [the upstream spreadsheet](https://docs.google.com/spreadsheets/d/1GDNEzJe_rWdM3oG_kbBEH8r11Pcy4a1xJ1oglVBsZRE/edit?usp=sharing) and the corresponding Behat contexts in the `master` branch. It will be included in the 3.x release. Thanks for the help!
