### ISSUE TITLE
Correct machine name maximum length for workflows, states, and transitions

### ISSUE THREAD

**Issue by dangur** [acquia/drupal-spec-tool#25]
Machine names can only be a maximum of 26 characters. Add validation to machine name columns with the custom formula `=LEN($E:$E)<=26`.

**Comment by TravisCarden** [comment]
Hello, @dangur. The maximum length for all machine names that I know of is, in fact, 32. Machine names for fields created via the UI, however, include a prefix of "field_", which reduces their _available_ length to 26. Is that what you're referring to? If so, be sure to include "field_" in the spreadsheet. Unfortunately, I can't just assume that all field machine names begin that way, because not all do. The out-of-the-box Body field, for example, has a machine name of "body".

**Comment by dangur** [comment]
I see @TravisCarden , so the formulas would need to be `=LEN($E:$E)<=32` for fields and `=LEN($C:$C)<=32` for bundles, menus, views, image styles, migrations, workflows, and user roles. The formulas for views displays, workflow states, and workflow transitions would be `=LEN($D:$D)<=32`.

**Comment by TravisCarden** [comment]
I double checked, @dangur, and it turns out that Workflows, Workflow states, and Workflow transitions machine names (oddly enough) have a maximum length of 64 characters, so I updated those in [the upstream sheet](https://docs.google.com/spreadsheets/d/1GDNEzJe_rWdM3oG_kbBEH8r11Pcy4a1xJ1oglVBsZRE/edit?usp=sharing). Migrations aren't created via the UI, so their IDs don't have an obvious maximum length. (I'm sure there's a technical limit imposed somewhere deeper than I care to look at the moment. If you can turn one up and point me to it, I'll gladly add validation.) I think everything is correct now. Thanks!
