### ISSUE TITLE
Handle other entity types

### ISSUE THREAD

**Issue by philippemouchel** [acquia/drupal-spec-tool#53]
Hi there.

I'm currently using this drupal-spec-tool on a Drupal Commerce site (D9 and DC2), and I had to edit ContentModelContext file to get Behat to acknowledge Drupal Commerce entities.
Here is the patch.

```
diff --git a/src/Context/ContentModelContext.php b/src/Context/ContentModelContext.php
index 739525f..7d50f4b 100644
--- a/src/Context/ContentModelContext.php
+++ b/src/Context/ContentModelContext.php
@@ -173,6 +173,17 @@ class ContentModelContext extends ContextBase {
   protected function getContentEntityTypes() {
     $ids = [
       'block_content',
+      'commerce_log',
+      'commerce_order',
+      'commerce_order_item',
+      'commerce_payment',
+      'commerce_payment_method',
+      'commerce_product',
+      'commerce_product_attribute_value',
+      'commerce_product_variation',
+      'commerce_promotion',
+      'commerce_promotion_coupon',
+      'commerce_store',
       'media',
       'node',
       'paragraph',

```

Any elegant way to do that ?
How about custom entities ?

**Comment by TravisCarden** [comment]
Hi, @philippemouchel. Definitely!

Simply subclass `ContentModelContext` and override `getContentEntityTypes()` with your customizations. Then update your Behat configuration to use your context instead of the Spec Tool's, e.g.:

```diff
 # behat.yml
 default:
   suites:
     default:
       contexts:
-        - Acquia\DrupalSpecTool\Context\ContentModelContext
+        - AcmeCorp\MyContentModelContext
```

As to custom entity types, as long as they implement `\Drupal\Core\Entity\ContentEntityInterface` you should be fine to add basic support for them in the same place. But I haven't investigated that, and there are bound to be unanticipated effects of including them. Good luck! 😄 

If you're looking for something more flexible for reuse across projects, or if you're interested in contributing to the Spec Tool itself, we could make the content entity types list configurable in `behat.yml`. Alternatively, we could just dynamically get all defined entity types that implement `ContentEntityInterface`--if that would even be desirable. If you're interested in working on something like that I may be able to give you some pointers. 👍

**Comment by mgreco-n** [comment]
Hello!
In my content_model.feature file I have the following line:
| Article (Content type) | Image | field_image | Entity reference | Required | 1 | Entity browser | | |

In the system I have implemented the field in question.

Running the test I get the following error message:
--- Missing fields (present in specification, absent from Drupal)
      | Article (Content type) | Image | field_image | Entity reference | Required | 1 | Entity browser |  |  | (TravisCarden\BehatTableComparison\UnequalTablesException)

Usually if there is something wrong with the test I can see the field in the unexpected fields list.
The system appears to be unable to detect this type of field. The same thing happens with users.

In my project I also used commerce and I solved the problem by modifying the getContentEntityTypes () method as shown by philippemouchel.
My system shows the error message posted below when I add the following ids in the array: 'commerce_log', 'commerce_payment_method''commerce_payment', 
**The "" entity type does not exist. (Drupal\Component\Plugin\Exception\PluginNotFoundException)**
The same error occurs when I add the to the array the 'user' id in an attempt to identify system users to conduct tests.

How is it possible to resolve the situation so that we can test for the entity reference Image and for the users?

Thank you for your kind attention and for the time dedicated.
I wish you a good day.

**Comment by TravisCarden** [comment]
@mgreco-n can you post a complete diff of the changes you made that you describe above?

**Comment by TravisCarden** [comment]
@Peppe87 are you trying to add support for user _roles_? That would be `user_role`, and there's another issue to (finish) adding support for them: https://github.com/acquia/drupal-spec-tool/issues/20.

**Comment by Peppe87** [comment]
No, just to check for fields on user entity.

**Comment by TravisCarden** [comment]
Oh... Now that you mention it, I remember looking at that ages ago, and as I recall user entities have a different API from other kinds. Why don't you create an issue for adding support for them and link to it here?
